table f_export_value
	lineageTag: 96f8db0b-1c0c-4e55-9682-f88cbe185b5c

	column 'Source.Name'
		dataType: string
		lineageTag: f4dd2e91-e8f0-47df-b3c4-193e62487e7e
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column @frequency
		dataType: string
		lineageTag: 79de6327-1a28-461c-86aa-b43d8ad2cc26
		summarizeBy: none
		sourceColumn: @frequency

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: 85148d1f-9a63-449e-a2dc-a5fa515809c6
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column dataset_code
		dataType: string
		lineageTag: 2c3adae9-0fee-401b-bbfc-d129237a3e2c
		summarizeBy: none
		sourceColumn: dataset_code

		annotation SummarizationSetBy = Automatic

	column dataset_name
		dataType: string
		lineageTag: fb85ccbd-d854-479c-a477-1de0dd751d89
		summarizeBy: none
		sourceColumn: dataset_name

		annotation SummarizationSetBy = Automatic

	column series_code
		dataType: string
		lineageTag: 606c9f5e-4e02-4680-b671-eb3967c5245d
		summarizeBy: none
		sourceColumn: series_code

		annotation SummarizationSetBy = Automatic

	column series_name
		dataType: string
		lineageTag: 4b342664-162c-4c80-9111-22dc3ce19909
		summarizeBy: none
		sourceColumn: series_name

		annotation SummarizationSetBy = Automatic

	column original_period
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfb65a2b-6b7e-4c2f-a22b-67288780d33b
		summarizeBy: none
		sourceColumn: original_period

		variation Variation
			isDefault
			relationship: da6f87fa-c293-4256-9c04-5a3942baf00c
			defaultHierarchy: LocalDateTable_4a7bf3ce-4222-44d5-a6d8-09c9299768ec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column period
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b24157c8-30e8-4b7c-a489-244b119dfa90
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column original_value
		dataType: double
		lineageTag: aa6dcd6b-43b9-4f5b-aaf5-67245fba5757
		summarizeBy: sum
		sourceColumn: original_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column value
		dataType: double
		lineageTag: 6e75726c-026a-4968-980a-318dc14496dd
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FREQ
		dataType: string
		lineageTag: 2796fc72-e18f-4bf5-98c0-ea76689167ce
		summarizeBy: none
		sourceColumn: FREQ

		annotation SummarizationSetBy = Automatic

	column REF_AREA
		dataType: string
		lineageTag: c76f5b45-9fbd-462d-b3aa-cf45903e84e0
		summarizeBy: none
		sourceColumn: REF_AREA

		annotation SummarizationSetBy = Automatic

	column INDICATOR
		dataType: string
		lineageTag: a08437a2-8a0b-4724-914c-15a77d5b7e1e
		summarizeBy: none
		sourceColumn: INDICATOR

		annotation SummarizationSetBy = Automatic

	column COUNTERPART_AREA
		dataType: string
		lineageTag: 7349b090-4075-41d4-b092-c0051a0eb7b8
		summarizeBy: none
		sourceColumn: COUNTERPART_AREA

		annotation SummarizationSetBy = Automatic

	column Frequency
		dataType: string
		lineageTag: 32cb833a-f387-4fa7-b1ad-e1a929fc0e67
		summarizeBy: none
		sourceColumn: Frequency

		annotation SummarizationSetBy = Automatic

	column 'Reference Area'
		dataType: string
		lineageTag: c6651491-1672-4bf3-ab67-df1c718c9d5b
		summarizeBy: none
		sourceColumn: Reference Area

		annotation SummarizationSetBy = Automatic

	column 'Indicator.1'
		dataType: string
		lineageTag: f2d120e1-e6c6-46f0-ab03-bef4ff5b7452
		summarizeBy: none
		sourceColumn: Indicator.1

		annotation SummarizationSetBy = Automatic

	column 'Counterpart Reference Area'
		dataType: string
		lineageTag: 70dfad92-d958-4e17-8cc3-f1bde0a46ba8
		summarizeBy: none
		sourceColumn: Counterpart Reference Area

		annotation SummarizationSetBy = Automatic

	partition f_export_value = m
		mode: import
		source =
				let
				    Source = Folder.Files("D:\Projects\DA Porforlio\data\ex"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"@frequency", type text}, {"provider_code", type text}, {"dataset_code", type text}, {"dataset_name", type text}, {"series_code", type text}, {"series_name", type text}, {"original_period", type date}, {"period", type date}, {"original_value", type number}, {"value", type number}, {"FREQ", type text}, {"REF_AREA", type text}, {"INDICATOR", type text}, {"COUNTERPART_AREA", type text}, {"Frequency", type text}, {"Reference Area", type text}, {"Indicator.1", type text}, {"Counterpart Reference Area", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

