table f_unemployment_rate
	lineageTag: de691d7e-f508-46d6-a84e-d516588d391a

	column Column1
		dataType: int64
		formatString: 0
		lineageTag: 3c7b5194-4319-48d3-b0fd-fd1cc2808de4
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column @frequency
		dataType: string
		lineageTag: 2ce5c1d6-931f-424b-8d58-07aad8114778
		summarizeBy: none
		sourceColumn: @frequency

		annotation SummarizationSetBy = Automatic

	column provider_code
		dataType: string
		lineageTag: d295bab9-635c-4e09-84a1-adda98b76e38
		summarizeBy: none
		sourceColumn: provider_code

		annotation SummarizationSetBy = Automatic

	column dataset_code
		dataType: string
		lineageTag: 228092ef-1428-44ce-86b4-8a88019f5f44
		summarizeBy: none
		sourceColumn: dataset_code

		annotation SummarizationSetBy = Automatic

	column dataset_name
		dataType: string
		lineageTag: a5ec1c5c-be2b-4dde-b850-13694e2b3767
		summarizeBy: none
		sourceColumn: dataset_name

		annotation SummarizationSetBy = Automatic

	column series_code
		dataType: string
		lineageTag: 21c154f2-3225-4c90-a5c9-72788d45bd01
		summarizeBy: none
		sourceColumn: series_code

		annotation SummarizationSetBy = Automatic

	column series_name
		dataType: string
		lineageTag: cdcf3834-ef5b-4c6c-b479-0a311783a550
		summarizeBy: none
		sourceColumn: series_name

		annotation SummarizationSetBy = Automatic

	column original_period
		dataType: int64
		formatString: 0
		lineageTag: b5a845c9-3009-4c46-8e25-bb9b24de6486
		summarizeBy: sum
		sourceColumn: original_period

		annotation SummarizationSetBy = Automatic

	column period
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f47311a5-ae44-4a16-a36b-883c18773493
		summarizeBy: none
		sourceColumn: period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column original_value
		dataType: string
		lineageTag: 9e445468-1f2d-4dd4-8fea-f87dd06434b3
		summarizeBy: none
		sourceColumn: original_value

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		lineageTag: b52591e1-e88c-4572-ac4a-88a3fdc87ae6
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weo-country
		dataType: string
		lineageTag: b942c71d-c348-4e84-b595-9897f34462bf
		summarizeBy: none
		sourceColumn: weo-country

		annotation SummarizationSetBy = Automatic

	column weo-subject
		dataType: string
		lineageTag: 5a8cc5e6-d82b-433d-805f-cdc9488eb7a7
		summarizeBy: none
		sourceColumn: weo-subject

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: ab3b0f2e-eddd-4626-a4b0-33814529cc56
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column 'WEO Country'
		dataType: string
		lineageTag: 1457fef0-0cc6-458f-8947-fc8803efa290
		summarizeBy: none
		sourceColumn: WEO Country

		annotation SummarizationSetBy = Automatic

	column 'WEO Subject'
		dataType: string
		lineageTag: cde8f4db-2210-4e61-a12a-c9a6067848ef
		summarizeBy: none
		sourceColumn: WEO Subject

		annotation SummarizationSetBy = Automatic

	column 'Unit.1'
		dataType: string
		lineageTag: bf6afb1c-601c-4fb3-818c-34492c4842e1
		summarizeBy: none
		sourceColumn: Unit.1

		annotation SummarizationSetBy = Automatic

	partition f_unemployment_rate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Projects\DA Porforlio\data\imf_unemployment_rate.csv"),[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"@frequency", type text}, {"provider_code", type text}, {"dataset_code", type text}, {"dataset_name", type text}, {"series_code", type text}, {"series_name", type text}, {"original_period", Int64.Type}, {"period", type date}, {"original_value", type text}, {"value", type number}, {"weo-country", type text}, {"weo-subject", type text}, {"unit", type text}, {"WEO Country", type text}, {"WEO Subject", type text}, {"Unit", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Unit", "Unit.1"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

